### ISSUE TITLE
TypeScript Starter Snake

### ISSUE THREAD

**Issue by kgorgi** [BattlesnakeOfficial/docs#11]
Hi! I have created a TypeScript starter snake using Battlesnake's official [JavaScript Starter Project](https://github.com/battlesnakeofficial/starter-snake-node). I decided to focus on two major aspects for this project:

1. Minimalistic project structure like the JavaScript Starter Project.
2. Solid type definitions. I have extensively commented the type definition file using the Battlesnake Docs.

I think this project is good for developers who want a simple barebones project like the JavaScript Starter Project but in TypeScript with detailed type definitions. What do you think and could this project be included on the Starter Projects page?

[TypeScript Starter Snake](https://github.com/kgorgi/starter-snake-node-ts) by [Kian Gorgichuk](https://github.com/kgorgi)

Thanks!

**Comment by bvanvugt** [comment]
@kgorgi Hey! This looks awesome. 

Our team should be able to review it this week and hopefully get it listed. We'll reach out here if we have any questions.

Cheers, 
Brad

**Comment by bvanvugt** [comment]
Got a chance to review this, looks great! I've added it to the docs here:
https://github.com/BattlesnakeOfficial/docs/commit/5337bb3563a90af526abb5974253ba6d9e4e66a2
