### ISSUE TITLE
Updating Object definition for Board in api.md

### ISSUE THREAD

**Issue by jp789** [BattlesnakeOfficial/docs#2]
I think the Board representation is not a standard grid.  The game is oriented with (0,0) in the top left rather than bottom left, and Y-axis is positive going down rather than up.

E.g. From a sample run of my battle snake, the starting position is (4,1) rather than (4,3) as one would expect in a standard grid.

![starting position](https://user-images.githubusercontent.com/13459921/83338920-f22c3900-a296-11ea-907f-dfcc26394652.png)

![snippet from log](https://user-images.githubusercontent.com/13459921/83338987-767ebc00-a297-11ea-95e6-7a76ddbce1f8.png)

**Comment by tyrelh** [comment]
This is already changed with API v1 to my knowledge. Reference the [official API docs](https://docs.battlesnake.com/references/api) to update your snake to use the new API.

If you are still using the old API you will get origin `{0, 0}` in the top-left.

If you update to use the latest API the origin `{0, 0}` will be in the bottom-left corner.

**Comment by jp789** [comment]
👍
