### ISSUE TITLE
Unclear description of customizations field of Battlesnake object

### ISSUE THREAD

**Issue by JaroPaska** [BattlesnakeOfficial/docs#28]
The [docs](https://docs.battlesnake.com/api/objects/battlesnake) state that the customizations field of a Battlesnake follows the same rules as the Info request. However, the Info request is required to contain an apiversion field, which the example customizations object does not contain.

What should the customizations object contain? I assume it has 3 fields: color, head and tail which are all required, but I am not sure.

**Comment by bvanvugt** [comment]
@JaroPaska updated, thanks!
