### ISSUE TITLE
starter snake julia

### ISSUE THREAD

**Issue by luigiannelli** [BattlesnakeOfficial/docs#35]
I have created a new starter-snake-julia in JULIA which is very similar to starter-snake-python.
the repository is at https://github.com/luigiannelli/starter-snake-julia
if you want you can add it to the community starter projects

**Comment by bvanvugt** [comment]
Great, thanks! Added to the new docs project here:
https://github.com/BattlesnakeOfficial/docs-new/commit/7057a836e952e335c39c7a74cb22ff5283f7b755
